/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GetData {
        "First": string;
        "Last": string;
        "Middle": string;
    }
    interface MyCard {
        "fname": string;
        "name": string;
    }
    interface SearchWorld {
        "SearchText": string;
    }
    interface SideDrawer {
        "open": boolean;
        "title": string;
    }
}
declare global {
    interface HTMLGetDataElement extends Components.GetData, HTMLStencilElement {
    }
    var HTMLGetDataElement: {
        prototype: HTMLGetDataElement;
        new (): HTMLGetDataElement;
    };
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLSearchWorldElement extends Components.SearchWorld, HTMLStencilElement {
    }
    var HTMLSearchWorldElement: {
        prototype: HTMLSearchWorldElement;
        new (): HTMLSearchWorldElement;
    };
    interface HTMLSideDrawerElement extends Components.SideDrawer, HTMLStencilElement {
    }
    var HTMLSideDrawerElement: {
        prototype: HTMLSideDrawerElement;
        new (): HTMLSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "get-data": HTMLGetDataElement;
        "my-card": HTMLMyCardElement;
        "search-world": HTMLSearchWorldElement;
        "side-drawer": HTMLSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface GetData {
        "First"?: string;
        "Last"?: string;
        "Middle"?: string;
    }
    interface MyCard {
        "fname"?: string;
        "name"?: string;
    }
    interface SearchWorld {
        "SearchText"?: string;
    }
    interface SideDrawer {
        "open"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "get-data": GetData;
        "my-card": MyCard;
        "search-world": SearchWorld;
        "side-drawer": SideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "get-data": LocalJSX.GetData & JSXBase.HTMLAttributes<HTMLGetDataElement>;
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "search-world": LocalJSX.SearchWorld & JSXBase.HTMLAttributes<HTMLSearchWorldElement>;
            "side-drawer": LocalJSX.SideDrawer & JSXBase.HTMLAttributes<HTMLSideDrawerElement>;
        }
    }
}
